SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ConsultaMedica;
DROP TABLE IF EXISTS ExameMedico;
DROP TABLE IF EXISTS ResultadoExame;
DROP TABLE IF EXISTS TipoExame;
DROP TABLE IF EXISTS CodigoDiagnostico;
DROP TABLE IF EXISTS Medico;
DROP TABLE IF EXISTS EmailMedico;
DROP TABLE IF EXISTS FoneMedico;
DROP TABLE IF EXISTS Paciente;
DROP TABLE IF EXISTS EmailPaciente;
DROP TABLE IF EXISTS Cidade;
DROP TABLE IF EXISTS UnidadeFederativa;
DROP TABLE IF EXISTS Endereco;
DROP TABLE IF EXISTS Bairro;
DROP TABLE IF EXISTS Logradouro;
DROP TABLE IF EXISTS TipoLogradouro;
DROP TABLE IF EXISTS FonePaciente;
DROP TABLE IF EXISTS ddd;
DROP TABLE IF EXISTS ddi;

SET FOREIGN_KEY_CHECKS = 1;
